//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("pcolor ver:1.4.21127.0")]
[assembly: AssemblyDescription("echos text to the console window using the specified colors.")]
[assembly: AssemblyCompany("Bricksoft.com")]
[assembly: AssemblyProduct("pcolor")]
[assembly: AssemblyCopyright("Copyright (C) 2010-2012 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("F05D9163-CE07-4CEE-AADE-AEE13A2BE86B")]
[assembly: AssemblyVersion("1.4.21127.0")]
[assembly: AssemblyFileVersion("1.4.21127.0")]


