//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("pcolor ver:1.4.8.51031")]
[assembly: System.Reflection.AssemblyDescription("echos text to the console window using the specified colors.")]
[assembly: System.Reflection.AssemblyCompany("Bricksoft.com")]
[assembly: System.Reflection.AssemblyProduct("pcolor")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) 2010-2015 Kody Brown.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("F05D9163-CE07-4CEE-AADE-AEE13A2BE86B")]
[assembly: System.Reflection.AssemblyVersion("1.4.8.51031")]
[assembly: System.Reflection.AssemblyFileVersion("1.4.8.51031")]


